### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by vrnagy** [1up-lab/OneupAclBundle#30]
Hello,

Do You plan a release for Symfony 3? (Without the 2.x support, but maintain the current branch until 2.8 EOL)
If You like, I can start to work in the issue.

**Comment by bytehead** [comment]
Hi Róbert

We could do. We actually not using this bundle for ourself anymore, because we go with [voters](http://symfony.com/doc/current/cookbook/security/acl.html).

> Alternatives to ACLs

> Using ACL's isn't trivial, and for simpler use cases, it may be overkill. If your permission logic could be  described by just writing some code (e.g. to check if a Blog is owned by the current User), then consider using voters. A voter is passed the object being voted on, which you can use to make complex decisions and effectively implement your own ACL. Enforcing authorization (e.g. the isGranted part) will look similar to what you see in this entry, but your voter class will handle the logic behind the scenes, instead of the ACL system.

But you're welcome with a PR :)
You will have to add `symfony/security-acl` to the project to have it in 3.0 [see more](symfony/security-acl).
